import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
# family = "FiraCode Nerd Font Mono"
family = "Maple Mono NF"
style = "Light"

[font.bold]
# family = "FiraCode Nerd Font Mono"
family = "Maple Mono NF"
style = "SemiBold"

[font.italic]
# family = "FiraCode Nerd Font Mono"
family = "Maple Mono NF"
style = "Light Italic"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Home"
chars = "\u001bOH"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Home"
chars = "\u001b[H"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "End"
chars = "\u001bOF"
mode = "AppCursor"

[[keyboard.bindings]]
key = "End"
chars = "\u001b[F"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command|Shift"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
chars = "\u001b[5;2~"

[[keyboard.bindings]]
key = "PageUp"
mods = "Control"
chars = "\u001b[5;5~"

[[keyboard.bindings]]
key = "PageUp"
chars = "\u001b[5~"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
chars = "\u001b[6;2~"

[[keyboard.bindings]]
key = "PageDown"
mods = "Control"
chars = "\u001b[6;5~"

[[keyboard.bindings]]
key = "PageDown"
chars = "\u001b[6~"

[[keyboard.bindings]]
key = "Left"
mods = "Shift"
chars = "\u001b[1;2D"

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001b[1;3D"

[[keyboard.bindings]]
key = "Left"
chars = "\u001b[D"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Left"
chars = "\u001bOD"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Right"
mods = "Shift"
chars = "\u001b[1;2C"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001b[1;3C"

[[keyboard.bindings]]
key = "Right"
chars = "\u001b[C"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Right"
chars = "\u001bOC"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Up"
mods = "Shift"
chars = "\u001b[1;2A"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[1;5A"

[[keyboard.bindings]]
key = "Up"
mods = "Alt"
chars = "\u001b[1;3A"

[[keyboard.bindings]]
key = "Up"
chars = "\u001b[A"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Up"
chars = "\u001bOA"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
chars = "\u001b[1;2B"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[1;5B"

[[keyboard.bindings]]
key = "Down"
mods = "Alt"
chars = "\u001b[1;3B"

[[keyboard.bindings]]
key = "Down"
chars = "\u001b[B"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Down"
chars = "\u001bOB"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Tab"
mods = "Shift"
chars = "\u001b[Z"

[[keyboard.bindings]]
key = "F1"
chars = "\u001bOP"

[[keyboard.bindings]]
key = "F2"
chars = "\u001bOQ"

[[keyboard.bindings]]
key = "F3"
chars = "\u001bOR"

[[keyboard.bindings]]
key = "F4"
chars = "\u001bOS"

[[keyboard.bindings]]
key = "F5"
chars = "\u001b[15~"

[[keyboard.bindings]]
key = "F6"
chars = "\u001b[17~"

[[keyboard.bindings]]
key = "F7"
chars = "\u001b[18~"

[[keyboard.bindings]]
key = "F8"
chars = "\u001b[19~"

[[keyboard.bindings]]
key = "F9"
chars = "\u001b[20~"

[[keyboard.bindings]]
key = "F10"
chars = "\u001b[21~"

[[keyboard.bindings]]
key = "F11"
chars = "\u001b[23~"

[[keyboard.bindings]]
key = "F12"
chars = "\u001b[24~"

[[keyboard.bindings]]
key = "Back"
chars = "\u007f"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u001b"

[[keyboard.bindings]]
key = "Insert"
chars = "\u001b[2~"

[[keyboard.bindings]]
key = "Delete"
chars = "\u001b[3~"

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0002&"

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0002c"

[[keyboard.bindings]]
key = "RBracket"
mods = "Command|Shift"
chars = "\u0002n"

[[keyboard.bindings]]
key = "LBracket"
mods = "Command|Shift"
chars = "\u0002p"

[[keyboard.bindings]]
key = "RBracket"
mods = "Command"
chars = "\u0002o"

[[keyboard.bindings]]
key = "LBracket"
mods = "Command"
chars = "\u0002;"

[[keyboard.bindings]]
key = "F"
mods = "Command"
chars = "\u0002/"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false
persistent_logging = false
log_level = "OFF"
print_events = false

[shell]
program = "/bin/zsh"
